### PR TITLE
remove yearly check in recurring cashflow

### LINKED ISSUE #9: [DEFECT] TEAL will not calculate yearly cashflow if in same processor
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
While using the same processor calculating multiple denoise, if pass-through different drivers of same recurring type cashflow variable. the Cash flow will not be calculated again.

##### What did you see instead?
The recurring cash flow will take the cashflow calculated before.

##### Do you have a suggested fix for the development team?
remove the `if self._yearlyCashflow is None` in Cashflows.py

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by JiaZhou-PU**
--------
Pull Request Description
--------
##### What issue does this change request address?
Close #9 
##### What are the significant changes in functionality due to this change request?
Remove a yearly check for recurring type cashflow

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [x] 4. Automated Tests should pass.
- [x] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [x] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
I did a code review and it generally looks fine.  I am curious why it always runs ```computeYearlyCashflow``` instead of setting ```self._yearlyCashflow``` to None to force the recalculation.  Also, the regression test failed.

If you can explain the above and fix the regression test (invalidating is fine if that works) I will approve it.  Thanks.

**Comment by joshua-cogliati-inl** [comment]
I invalidated the test and it failed again (and I checked and without this modification the tests pass), so I think the fail needs to be fixed.

**Comment by joshua-cogliati-inl** [comment]
I can take a look at the failing regression test, if you don't get to it in the next few days.

**Comment by JiaZhou-PU** [comment]
@joshua-cogliati-inl I can not saw the results but I am guessing it's the objective oriented one. I will trying to figure it out.

**Comment by joshua-cogliati-inl** [comment]
> @joshua-cogliati-inl I can not saw the results but I am guessing it's the objective oriented one. I will trying to figure it out.

Yes, it is the object oriented one.

```
Output of'/home/civet/civet/build_0/TEAL/tests/CashFlow_ObjectOriented':
Loading data ...
DEBUGG hourly recurring: [       0.         64852206.39932915 72129453.48280548 79597189.193351
 90012632.52779377]
DEBUGG yearly recurring: [   0.         7307.95967968 8110.60900484 8929.99979209 9768.00908894]
DEBUGG amortizing cf: Cap
DEBUGG amort alpha: [0.     0.3333 0.4445 0.1481 0.0741]
DEBUGG depre alpha: [ 0. -1. -1. -1. -1.]
CashFlow INFO (run): Starting CashFlow Run ...
CashFlow INFO (run): ... Checking if all drivers present ...
CashFlow INFO (checkDrivers): ... creating evaluation sequence ...
CashFlow INFO (checkDrivers): ... evaluation sequence: ['MainComponent|RecursHourly', 'MainComponent|RecursYearly', 'MainComponent|Cap', 'MainComponent|Cap', 'MainComponent|MainComponent_amortize_Cap', 'MainComponent|MainComponent_depreciate_Cap', 'EndNode']
CashFlow INFO (run): ==========================================================================================
CashFlow INFO (run): Component Lifetime Cashflow Calculations
CashFlow INFO (run): ==========================================================================================
CashFlow INFO (compLife): ---------------------------------------------------------------------------
DEBUGG comp: MainComponent <TEAL.src.CashFlows.Recurring object at 0x7f1ca5a77690>
CashFlow INFO (compLife): Computing LIFETIME cash flow for Component "MainComponent" CashFlow "RecursHourly" ...
Traceback (most recent call last):
  File "HourlyObjectOrientedTest.py", line 198, in <module>
    metrics = run(df)
  File "HourlyObjectOrientedTest.py", line 38, in run
    metrics = RunCashFlow.run(settings, list(components.values()), {})
  File "/home/civet/civet/build_0/TEAL/src/main.py", line 566, in run
    lifeCf = componentLifeCashflow(comp, cf, variables, lifetimeCashflows, v=0)
  File "/home/civet/civet/build_0/TEAL/src/main.py", line 203, in componentLifeCashflow
    results = cf.calculateCashflow(variables, lifetimeCashflows, comp.getLifetime()+1, v)
  File "/home/civet/civet/build_0/TEAL/src/CashFlows.py", line 1042, in calculateCashflow
    need = self.loadFromVariables(need, variables, lifetimeCashflows, lifetime)
  File "/home/civet/civet/build_0/TEAL/src/CashFlows.py", line 758, in loadFromVariables
    need = self.extendParameters(need, lifetime)
  File "/home/civet/civet/build_0/TEAL/src/CashFlows.py", line 1067, in extendParameters
    if utils.isAFloatOrInt(value) or (len(value) == 1 and utils.isAFloatOrInt(value[0])):
TypeError: object of type 'NoneType' has no len()

Running test failed with exit code 1
(12/12) Failed (  1.83sec)/home/civet/civet/build_0/TEAL/tests/CashFlow_ObjectOriented
```

**Review by joshua-cogliati-inl — APPROVED** [review]
Code reviewed, and I approve.

**Comment by alfoa** [comment]
@wangcj05

**Comment by wangcj05** [comment]
@JiaZhou-PU @PaulTalbot-INL @alfoa
The changes by this CR breaks LOGOS plugins. The reason for that is LOGOS calculates the cash flows by itself and sends the calculated cash flows to TEAL for the NPV calculation. With the new changes, it forces TEAL to recompute the cash flows for each run, and the original computed cash flows will be overwritten. This actually blocks the option to let the user to provided already calculated cashflows. To me, I think it is better to keep this option.

**Comment by wangcj05** [comment]
> @wangcj05

Thanks, @alfoa I posted in the wrong place.

**Comment by JiaZhou-PU** [comment]
@wangcj05, Yes, I was trying to have a discussion about this but no sure if this is suited for all use cases. See comment: https://github.com/idaholab/TEAL/issues/9#issuecomment-696928623

**Comment by JiaZhou-PU** [comment]
@wangcj05 I have the same situation that my dispatcher needs to calculate the yearly cash flow itself, however, because my runs are synthetic, I will send in different yearly cash flow for all the runs. Then I find out if yearly cashflow is already calculated before for different run, TEAL will store this value and never changed. It's actually not blocking you from providing your cash flow, instead, you could still provide alpha or driver to TEAL.
Because my cases will need those different cashflows I need the option to reassign different yearly cashflows. And if you could saw the calculation on the Capex, it is never checked whether the yearly cash flow is calculated. 
I was having doubts about this option: 
1) if yearly cashflow alpha or driver provided for new runs, and yearly cash flow will be recalculated, will this value change from the original stored value?
2)If restore this option, but for each run, I provide different alpha or driver, how can I make sure the yearly cash flow is not only from the 1st run?

**Comment by wangcj05** [comment]
@JiaZhou-PU I agree with you. The problem is TEAL will recalculate the cash flows. The users need to set alpha and driver to 1 in order to get the same cash flows. In your case, can you reset the yearly cashflow after each runs?

**Comment by JiaZhou-PU** [comment]
@wangcj05 I am reseting the yearly cash flow by sending different alphas. I dont know how to reset the yearly cashflow after each runs...

**Comment by PaulTalbot-INL** [comment]
I think the original intent was that `_yearly_cashflows` was temporary "hourly" storage to be filled in once, then collapsed during CashFlow computation; it was probably poorly designed as a destructive process, but I think as @wangcj05 mentioned, an automated way to collapse those cashflows might be the easiest thing?

Except ... we probably need a flag on whether to reset them or not, because in optimization searches it gets called a bunch of times and shouldn't be collapsed ... I think. We really, really, really need to design how we want this to be interacted with as a library, as it's very disjointed as it is now (my bad).

**Pull request merged**
